apiVersion: app/v1
kind: Service
metadata:
  name: backend-service
matchLabels:
  app: backend-restapp
  tier: backend
spec:
  selector:
    app: backend-restapp
  ports:
  - port: 8080
    targetPort: 8080
