apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-restapp
  template:
    metadata:
      labels:
        app: backend-restapp
    spec:
      containers:
      - name: backend-restapp
        image: stacksimplify/kube-helloworld:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
