apiVersion: v1
kind: Service
metadata:
  name: frontend-nginxapp-service
  labels: 
    app: frontend-nginxapp
    
spec:
  type: NodePort
  selector:
    app: frontend-nginxapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31234
